#ifndef _SAFE_ARITHMETIC_H_
#define _SAFE_ARITHMETIC_H_

EFI_STATUS EFIAPI UintnAdd(IN UINTN Arg1, IN UINTN Arg2, OUT UINTN* Sum);
EFI_STATUS EFIAPI Uint32Add(IN UINT32 Arg1, IN UINT32 Arg2, OUT UINT32* Sum);
EFI_STATUS EFIAPI UintnMult(IN UINTN Arg1, IN UINTN Arg2, OUT UINTN* Product);
EFI_STATUS EFIAPI Uint32Mult(IN UINT32 Arg1, IN UINT32 Arg2, OUT UINT32* Product);

#endif // _SAFE_ARITHMETIC_H_
