#ifndef _NETWORK_CONFIG_H_
#define _NETWORK_CONFIG_H_

// Buffer lengths
// MODIFY THIS VALUE TO MODIFY THE PACKET SIZE USED DURING FLASHING
#define NETWORK_BUFFER_SIZE 2 * 1024 * 1024
// 1000 is subtracted from the buffer size as the host appears to send messages slightly larger
// than the reported payload size.
#define NETWORK_MSG_PAYLOAD_SIZE NETWORK_BUFFER_SIZE - 1000
#define NETWORK_TRANSFER_SIZE    NETWORK_MSG_PAYLOAD_SIZE + sizeof(sNETWORK_HEADER)

// DHCP settings
#define NETWORK_DHCP_DISCOVER_TRY_COUNT 0
#define NETWORK_DHCP_DISCOVER_TIMEOUT   NULL
#define NETWORK_DHCP_REQUEST_TRY_COUNT  0
#define NETWORK_DHCP_REQUEST_TIMEOUT    NULL

// TCP settings
// BUG 18837367: Device never appears to disconnect from host if
// disconnected from network for a long period of time
#define NETWORK_TCP_TYPE_OF_SERVICE                          0
#define NETWORK_TCP_TIME_TO_LIVE                             0
#define NETWORK_TCP_ACCESS_POINT_USE_DEFAULT_ADDRESS         TRUE
#define NETWORK_TCP_ACCESS_POINT_STATION_PORT                62409
#define NETWORK_TCP_ACCESS_POINT_STATION_PORT_MIN            62409
#define NETWORK_TCP_ACCESS_POINT_STATION_PORT_MAX            62410
#define NETWORK_TCP_ACCESS_POINT_REMOTE_ADDRESS              0
#define NETWORK_TCP_ACCESS_POINT_REMOTE_PORT                 0
#define NETWORK_TCP_ACCESS_POINT_ACTIVE_FLAG                 FALSE
#define NETWORK_TCP_CONTROL_OPTION_RECEIVE_BUFFER_SIZE       NETWORK_BUFFER_SIZE
#define NETWORK_TCP_CONTROL_OPTION_SEND_BUFFER_SIZE          NETWORK_BUFFER_SIZE
#define NETWORK_TCP_CONTROL_OPTION_MAX_SYN_BACK_LOG          0
#define NETWORK_TCP_CONTROL_OPTION_CONNECTION_TIMEOUT        0
#define NETWORK_TCP_CONTROL_OPTION_DATA_RETRIES              6
#define NETWORK_TCP_CONTROL_OPTION_FIN_TIMEOUT               0
#define NETWORK_TCP_CONTROL_OPTION_TIME_WAIT_TIMEOUT         0
#define NETWORK_TCP_CONTROL_OPTION_KEEP_ALIVE_PROBES         4
#define NETWORK_TCP_CONTROL_OPTION_KEEP_ALIVE_TIME           0
#define NETWORK_TCP_CONTROL_OPTION_KEEP_ALIVE_INTERVAL       0
#define NETWORK_TCP_CONTROL_OPTION_ENABLE_NAGLE              FALSE
#define NETWORK_TCP_CONTROL_OPTION_ENABLE_TIME_STAMP         FALSE
#define NETWORK_TCP_CONTROL_OPTION_ENABLE_WINDOW_SCALING     TRUE
#define NETWORK_TCP_CONTROL_OPTION_ENABLE_SELECTIVE_ACK      FALSE
#define NETWORK_TCP_CONTROL_OPTION_ENABLE_PATH_MTU_DISCOVERY FALSE

// Timeouts
#define NETWORK_ACTIVE_CONNECT_TIMEOUT SEC_TO_100_NS(10)
#define NETWORK_CONNECT_TIMEOUT        0
#define NETWORK_LISTEN_TIMEOUT         0
#define NETWORK_CLOSE_TIMEOUT          SEC_TO_100_NS(5)
#define NETWORK_RECEIVE_TIMEOUT        SEC_TO_100_NS(25)
#define NETWORK_TRANSMIT_TIMEOUT       SEC_TO_100_NS(5)

#endif // _NETWORK_CONFIG_H_
